'use strict';

var regions = [

    "Alb-Donau-Kreis und Stadt Ulm",
    "Altmarkkreis Salzwedel",
    "Berlin",
    "Bodenseekreis",
    "Bundesstadt Bonn",
    "Burgenlandkreis",
    "Donnersbergkreis",
    "Eifelkreis Bitburg-Prüm",
    "Ennepe-Ruhr-Kreis",
    "Enzkreis und Stadt Pforzheim",
    "Erzgebirgskreis",
    "Hansestadt Bremen",
    "Hansestadt Hamburg",
    "Hansestadt Lübeck",
    "Hansestadt Rostock",
    "Heidekreis",
    "Hochsauerlandkreis",
    "Hochtaunuskreis",
    "Hohenlohekreis",
    "Ilm-Kreis",
    "Insel Borkum",
    "Insel Helgoland",
    "Kreis Ahrweiler",
    "Kreis Aichach-Friedberg",
    "Kreis Altenburger Land",
    "Kreis Altenkirchen",
    "Kreis Altötting",
    "Kreis Alzey-Worms",
    "Kreis Amberg-Sulzbach",
    "Kreis Ammerland",
    "Kreis Anhalt-Bitterfeld",
    "Kreis Aurich - Binnenland",
    "Kreis Aurich - Küste",
    "Kreis Bad Dürkheim",
    "Kreis Bad Kissingen",
    "Kreis Bad Kreuznach",
    "Kreis Bad Tölz-Wolfratshausen",
    "Kreis Barnim",
    "Kreis Bautzen - Bergland",
    "Kreis Bautzen - Tiefland",
    "Kreis Berchtesgadener Land",
    "Kreis Bergstraße",
    "Kreis Bernkastel-Wittlich",
    "Kreis Biberach",
    "Kreis Birkenfeld",
    "Kreis Borken",
    "Kreis Breisgau-Hochschwarzwald und Stadt Freiburg",
    "Kreis Böblingen",
    "Kreis Börde",
    "Kreis Calw",
    "Kreis Celle",
    "Kreis Cham",
    "Kreis Cloppenburg",
    "Kreis Cochem-Zell",
    "Kreis Coesfeld",
    "Kreis Cuxhaven - Binnenland",
    "Kreis Cuxhaven - Küste",
    "Kreis Dachau",
    "Kreis Dahme-Spreewald",
    "Kreis Darmstadt-Dieburg und Stadt Darmstadt",
    "Kreis Deggendorf",
    "Kreis Diepholz",
    "Kreis Dillingen a.d. Donau",
    "Kreis Dingolfing-Landau",
    "Kreis Dithmarschen - Binnenland",
    "Kreis Dithmarschen - Küste",
    "Kreis Donau-Ries",
    "Kreis Düren",
    "Kreis Ebersberg",
    "Kreis Eichsfeld",
    "Kreis Eichstätt",
    "Kreis Elbe-Elster",
    "Kreis Emmendingen",
    "Kreis Emsland",
    "Kreis Erding",
    "Kreis Erlangen-Höchstadt",
    "Kreis Esslingen",
    "Kreis Euskirchen",
    "Kreis Forchheim",
    "Kreis Freising",
    "Kreis Freudenstadt",
    "Kreis Freyung-Grafenau",
    "Kreis Friesland - Binnenland",
    "Kreis Friesland - Küste",
    "Kreis Fulda",
    "Kreis Fürstenfeldbruck",
    "Kreis Garmisch-Partenkirchen",
    "Kreis Germersheim",
    "Kreis Gießen",
    "Kreis Gifhorn",
    "Kreis Goslar",
    "Kreis Gotha",
    "Kreis Grafschaft Bentheim",
    "Kreis Greiz",
    "Kreis Groß-Gerau",
    "Kreis Göppingen",
    "Kreis Görlitz - Bergland",
    "Kreis Görlitz - Tiefland",
    "Kreis Göttingen",
    "Kreis Günzburg",
    "Kreis Gütersloh",
    "Kreis Hameln-Pyrmont",
    "Kreis Harburg",
    "Kreis Harz - Bergland",
    "Kreis Harz - Tiefland",
    "Kreis Havelland",
    "Kreis Haßberge",
    "Kreis Heidenheim",
    "Kreis Heinsberg",
    "Kreis Helmstedt",
    "Kreis Herford",
    "Kreis Hersfeld-Rotenburg",
    "Kreis Herzogtum Lauenburg",
    "Kreis Hildburghausen",
    "Kreis Hildesheim",
    "Kreis Holzminden",
    "Kreis Höxter",
    "Kreis Jerichower Land",
    "Kreis Kelheim",
    "Kreis Kitzingen",
    "Kreis Kleve",
    "Kreis Konstanz",
    "Kreis Kronach",
    "Kreis Kulmbach",
    "Kreis Kusel",
    "Kreis Landsberg am Lech",
    "Kreis Leer (ohne Borkum)",
    "Kreis Leipzig",
    "Kreis Lichtenfels",
    "Kreis Limburg-Weilburg",
    "Kreis Lindau (Bodensee)",
    "Kreis Lippe",
    "Kreis Ludwigsburg",
    "Kreis Ludwigslust-Parchim - Ost",
    "Kreis Ludwigslust-Parchim - West",
    "Kreis Lörrach",
    "Kreis Lüchow-Dannenberg",
    "Kreis Lüneburg",
    "Kreis Main-Spessart",
    "Kreis Mainz-Bingen und Stadt Mainz",
    "Kreis Mansfeld-Südharz",
    "Kreis Marburg-Biedenkopf",
    "Kreis Mayen-Koblenz",
    "Kreis Mecklenburgische Seenplatte - Nord",
    "Kreis Mecklenburgische Seenplatte - Südost",
    "Kreis Mecklenburgische Seenplatte - West",
    "Kreis Meißen",
    "Kreis Merzig-Wadern",
    "Kreis Mettmann",
    "Kreis Miesbach",
    "Kreis Miltenberg",
    "Kreis Minden-Lübbecke",
    "Kreis Mittelsachsen - Bergland",
    "Kreis Mittelsachsen - Tiefland",
    "Kreis Märkisch-Oderland",
    "Kreis Mühldorf a. Inn",
    "Kreis Neu-Ulm",
    "Kreis Neuburg-Schrobenhausen",
    "Kreis Neumarkt i.d. OPf.",
    "Kreis Neunkirchen",
    "Kreis Neustadt a.d. Aisch - Bad Windsheim",
    "Kreis Neustadt a.d. Waldnaab",
    "Kreis Neuwied",
    "Kreis Nienburg",
    "Kreis Nordfriesland - Binnenland",
    "Kreis Nordfriesland - Küste",
    "Kreis Nordhausen",
    "Kreis Nordsachsen - Nord",
    "Kreis Nordsachsen - Süd",
    "Kreis Nordwestmecklenburg - Binnenland",
    "Kreis Nordwestmecklenburg - Küste",
    "Kreis Northeim",
    "Kreis Nürnberger Land",
    "Kreis Oberallgäu",
    "Kreis Oberhavel",
    "Kreis Oberspreewald-Lausitz",
    "Kreis Oder-Spree",
    "Kreis Olpe",
    "Kreis Ostallgäu",
    "Kreis Osterholz",
    "Kreis Ostholstein - Binnenland",
    "Kreis Ostholstein - Küste",
    "Kreis Ostprignitz-Ruppin",
    "Kreis Paderborn",
    "Kreis Peine",
    "Kreis Pfaffenhofen a.d. Ilm",
    "Kreis Pinneberg",
    "Kreis Plön - Binnenland",
    "Kreis Plön - Küste",
    "Kreis Potsdam-Mittelmark",
    "Kreis Prignitz",
    "Kreis Rastatt",
    "Kreis Ravensburg",
    "Kreis Recklinghausen",
    "Kreis Regen",
    "Kreis Rendsburg-Eckernförde - Binnenland",
    "Kreis Rendsburg-Eckernförde - Küste",
    "Kreis Reutlingen",
    "Kreis Rhön-Grabfeld",
    "Kreis Rostock - Binnenland Nord",
    "Kreis Rostock - Binnenland Süd",
    "Kreis Rostock - Küste",
    "Kreis Rotenburg (Wümme)",
    "Kreis Roth",
    "Kreis Rottal-Inn",
    "Kreis Rottweil",
    "Kreis Saalfeld-Rudolstadt",
    "Kreis Saarlouis",
    "Kreis Schaumburg",
    "Kreis Schleswig-Flensburg - Binnenland",
    "Kreis Schleswig-Flensburg - Küste",
    "Kreis Schmalkalden-Meiningen",
    "Kreis Schwandorf",
    "Kreis Schwäbisch Hall",
    "Kreis Segeberg",
    "Kreis Siegen-Wittgenstein",
    "Kreis Sigmaringen",
    "Kreis Soest",
    "Kreis Sonneberg",
    "Kreis Spree-Neiße",
    "Kreis St. Wendel",
    "Kreis Stade",
    "Kreis Starnberg",
    "Kreis Steinburg",
    "Kreis Steinfurt",
    "Kreis Stendal",
    "Kreis Stormarn",
    "Kreis Straubing-Bogen und Stadt Straubing",
    "Kreis Sächsische Schweiz-Osterzgebirge - Tiefland",
    "Kreis Sächsische Schweiz-Osterzgebirge - ostelbisches Bergland",
    "Kreis Sächsische Schweiz-Osterzgebirge - westelbisches Bergland",
    "Kreis Sömmerda",
    "Kreis Südliche Weinstraße",
    "Kreis Südwestpfalz und Stadt Pirmasens",
    "Kreis Teltow-Fläming",
    "Kreis Tirschenreuth",
    "Kreis Traunstein",
    "Kreis Trier-Saarburg und Stadt Trier",
    "Kreis Tuttlingen",
    "Kreis Tübingen",
    "Kreis Uckermark",
    "Kreis Uelzen",
    "Kreis Unna",
    "Kreis Unterallgäu",
    "Kreis Vechta",
    "Kreis Verden",
    "Kreis Viersen",
    "Kreis Vorpommern-Greifswald - Binnenland Nord",
    "Kreis Vorpommern-Greifswald - Binnenland Süd",
    "Kreis Vorpommern-Greifswald - Küste Nord",
    "Kreis Vorpommern-Greifswald - Küste Süd",
    "Kreis Vorpommern-Rügen - Binnenland",
    "Kreis Vorpommern-Rügen - Insel Rügen",
    "Kreis Vorpommern-Rügen - Küste",
    "Kreis Vulkaneifel",
    "Kreis Waldeck-Frankenberg",
    "Kreis Waldshut",
    "Kreis Warendorf",
    "Kreis Weilheim-Schongau",
    "Kreis Weimarer Land",
    "Kreis Weißenburg-Gunzenhausen",
    "Kreis Wesel",
    "Kreis Wesermarsch - Binnenland",
    "Kreis Wesermarsch - Küste",
    "Kreis Wittenberg",
    "Kreis Wittmund - Binnenland",
    "Kreis Wittmund - Küste",
    "Kreis Wolfenbüttel",
    "Kreis Wunsiedel",
    "Kreis Zwickau - Bergland",
    "Kreis Zwickau - Tiefland",
    "Kreis und Stadt Ansbach",
    "Kreis und Stadt Aschaffenburg",
    "Kreis und Stadt Augsburg",
    "Kreis und Stadt Bamberg",
    "Kreis und Stadt Bayreuth",
    "Kreis und Stadt Coburg",
    "Kreis und Stadt Fürth",
    "Kreis und Stadt Heilbronn",
    "Kreis und Stadt Hof",
    "Kreis und Stadt Kaiserslautern",
    "Kreis und Stadt Karlsruhe",
    "Kreis und Stadt Kassel",
    "Kreis und Stadt Landshut",
    "Kreis und Stadt München",
    "Kreis und Stadt Offenbach",
    "Kreis und Stadt Oldenburg",
    "Kreis und Stadt Osnabrück",
    "Kreis und Stadt Passau",
    "Kreis und Stadt Regensburg",
    "Kreis und Stadt Rosenheim",
    "Kreis und Stadt Schweinfurt",
    "Kreis und Stadt Würzburg",
    "Kyffhäuserkreis",
    "Lahn-Dill-Kreis",
    "Main-Kinzig-Kreis und Stadt Hanau",
    "Main-Tauber-Kreis",
    "Main-Taunus-Kreis",
    "Märkischer Kreis",
    "Neckar-Odenwald-Kreis",
    "Oberbergischer Kreis",
    "Odenwaldkreis",
    "Ortenaukreis",
    "Ostalbkreis",
    "Region Hannover",
    "Regionalverband Saarbrücken",
    "Rems-Murr-Kreis",
    "Rhein-Erft-Kreis",
    "Rhein-Hunsrück-Kreis",
    "Rhein-Kreis Neuss",
    "Rhein-Lahn-Kreis",
    "Rhein-Neckar-Kreis und Stadt Heidelberg",
    "Rhein-Pfalz-Kreis und Stadt Ludwigshafen",
    "Rhein-Sieg-Kreis",
    "Rheingau-Taunus-Kreis",
    "Rheinisch-Bergischer Kreis",
    "Saale-Holzland-Kreis",
    "Saale-Orla-Kreis",
    "Saalekreis",
    "Saarpfalz-Kreis",
    "Salzlandkreis",
    "Schwalm-Eder-Kreis",
    "Schwarzwald-Baar-Kreis",
    "Stadt Amberg",
    "Stadt Baden-Baden",
    "Stadt Bielefeld",
    "Stadt Bochum",
    "Stadt Bottrop",
    "Stadt Brandenburg",
    "Stadt Braunschweig",
    "Stadt Bremerhaven",
    "Stadt Chemnitz",
    "Stadt Cottbus",
    "Stadt Delmenhorst",
    "Stadt Dessau-Roßlau",
    "Stadt Dortmund",
    "Stadt Dresden",
    "Stadt Duisburg",
    "Stadt Düsseldorf",
    "Stadt Eisenach",
    "Stadt Emden",
    "Stadt Erfurt",
    "Stadt Erlangen",
    "Stadt Essen",
    "Stadt Flensburg",
    "Stadt Frankenthal",
    "Stadt Frankfurt (Oder)",
    "Stadt Frankfurt am Main",
    "Stadt Gelsenkirchen",
    "Stadt Gera",
    "Stadt Hagen",
    "Stadt Halle (Saale)",
    "Stadt Hamm",
    "Stadt Herne",
    "Stadt Ingolstadt",
    "Stadt Jena",
    "Stadt Kaufbeuren",
    "Stadt Kempten (Allgäu)",
    "Stadt Kiel",
    "Stadt Koblenz",
    "Stadt Krefeld",
    "Stadt Köln",
    "Stadt Landau in der Pfalz",
    "Stadt Leipzig",
    "Stadt Leverkusen",
    "Stadt Magdeburg",
    "Stadt Mannheim",
    "Stadt Memmingen",
    "Stadt Mönchengladbach",
    "Stadt Mülheim an der Ruhr",
    "Stadt Münster",
    "Stadt Neumünster",
    "Stadt Neustadt an der Weinstraße",
    "Stadt Nürnberg",
    "Stadt Oberhausen",
    "Stadt Potsdam",
    "Stadt Remscheid",
    "Stadt Salzgitter",
    "Stadt Schwabach",
    "Stadt Schwerin",
    "Stadt Solingen",
    "Stadt Speyer",
    "Stadt Stuttgart",
    "Stadt Suhl",
    "Stadt Weiden in der Oberpfalz",
    "Stadt Weimar",
    "Stadt Wiesbaden",
    "Stadt Wilhelmshaven",
    "Stadt Wolfsburg",
    "Stadt Worms",
    "Stadt Wuppertal",
    "Stadt Zweibrücken",
    "StädteRegion Aachen",
    "Unstrut-Hainich-Kreis",
    "Vogelsbergkreis",
    "Vogtlandkreis - Bergland",
    "Vogtlandkreis - Tiefland",
    "Wartburgkreis",
    "Werra-Meissner-Kreis",
    "Westerwaldkreis",
    "Wetteraukreis",
    "Zollernalbkreis",
];

if (typeof module !== 'undefined' && module.parent) {
    module.exports = regions;
}
