var regions = [
	"Östliches Münsterland",
	"Östliches Ruhrgebiet",
	"östlich Fehmarn bis Rügen",
	"östlich Rügen",
	"(Reg.-Bez) Rheinland-Pfalz - West",
	"Alb-Donau-Kreis und Stadt Ulm",
	"Alster",
	"Altmühlsee/Brombachsee/Igelsbachsee",
	"Altmarkkreis Salzwedel",
	"Ammersee",
	"Baden-Württemberg",
	"Bayern",
	"Belte und Sund",
	"Bergisches Land",
	"Berlin",
	"Boddengewässer Ost",
	"Bodensee - Mitte",
	"Bodensee - Ost",
	"Bodensee - West",
	"Bodensee DACH",
	"Bodenseekreis",
	"Brandenburg - Ost",
	"Brandenburg - West",
	"Brandenburg",
	"Brandenburg/Berlin",
	"Bremen",
	"Bundesstadt Bonn",
	"Burgenlandkreis",
	"Chiemsee",
	"Dümmer See",
	"Deutsche Bucht",
	"Dogger",
	"Donnersbergkreis",
	"Edersee",
	"Eifel",
	"Eifelkreis Bitburg-Prüm",
	"Elbe von Hamburg bis Cuxhaven",
	"Elbe-/Wesermündung",
	"Elbe-Weser-Gebiet",
	"Elbemündung",
	"Englischer Kanal Ostteil",
	"Englischer Kanal Westteil",
	"Ennepe-Ruhr-Kreis",
	"Enzkreis und Stadt Pforzheim",
	"Erzgebirgskreis",
	"Fischer",
	"Flensburg bis Fehmarn",
	"Forggensee",
	"Forties",
	"Haarstrang",
	"Hamburg",
	"Hansestadt Bremen",
	"Hansestadt Hamburg",
	"Hansestadt Lübeck",
	"Hansestadt Rostock",
	"Harz",
	"Heidekreis",
	"Helgoland",
	"Hessen",
	"Hochsauerlandkreis",
	"Hochtaunuskreis",
	"Hohenlohekreis",
	"Hunsrück-Mosel",
	"Ijsselmeer",
	"Ilm-Kreis",
	"Insel Borkum",
	"Insel Helgoland",
	"Köln-Niederrheinische Bucht",
	"Kattegat",
	"Kinzig-Region",
	"Kreis Ahrweiler",
	"Kreis Aichach-Friedberg",
	"Kreis Altötting",
	"Kreis Altenburger Land",
	"Kreis Altenkirchen",
	"Kreis Alzey-Worms",
	"Kreis Amberg-Sulzbach",
	"Kreis Ammerland",
	"Kreis Anhalt-Bitterfeld",
	"Kreis Aurich - Binnenland",
	"Kreis Aurich - Küste",
	"Kreis Böblingen",
	"Kreis Börde",
	"Kreis Bad Dürkheim",
	"Kreis Bad Kissingen",
	"Kreis Bad Kreuznach",
	"Kreis Bad Tölz-Wolfratshausen",
	"Kreis Barnim",
	"Kreis Bautzen - Bergland",
	"Kreis Bautzen - Tiefland",
	"Kreis Bautzen",
	"Kreis Berchtesgadener Land",
	"Kreis Bergstraße",
	"Kreis Bernkastel-Wittlich",
	"Kreis Biberach",
	"Kreis Birkenfeld",
	"Kreis Borken",
	"Kreis Breisgau-Hochschwarzwald und Stadt Freiburg",
	"Kreis Burgenland",
	"Kreis Calw",
	"Kreis Celle",
	"Kreis Cham",
	"Kreis Cloppenburg",
	"Kreis Cochem-Zell",
	"Kreis Coesfeld",
	"Kreis Cuxhaven - Binnenland",
	"Kreis Cuxhaven - Küste",
	"Kreis Düren",
	"Kreis Dachau",
	"Kreis Dahme-Spreewald",
	"Kreis Darmstadt-Dieburg und Stadt Darmstadt",
	"Kreis Deggendorf",
	"Kreis Diepholz",
	"Kreis Dillingen a.d. Donau",
	"Kreis Dillingen a.d.Donau",
	"Kreis Dingolfing-Landau",
	"Kreis Dithmarschen - Binnenland",
	"Kreis Dithmarschen - Küste",
	"Kreis Donau-Ries",
	"Kreis Ebersberg",
	"Kreis Eichsfeld",
	"Kreis Eichstätt",
	"Kreis Elbe-Elster",
	"Kreis Emmendingen",
	"Kreis Emsland",
	"Kreis Erding",
	"Kreis Erlangen-Höchstadt",
	"Kreis Esslingen",
	"Kreis Euskirchen",
	"Kreis Fürstenfeldbruck",
	"Kreis Forchheim",
	"Kreis Freising",
	"Kreis Freudenstadt",
	"Kreis Freyung-Grafenau",
	"Kreis Friesland - Binnenland",
	"Kreis Friesland - Küste",
	"Kreis Fulda",
	"Kreis Göppingen",
	"Kreis Görlitz - Bergland",
	"Kreis Görlitz - Tiefland",
	"Kreis Görlitz",
	"Kreis Günzburg",
	"Kreis Gütersloh",
	"Kreis Garmisch-Partenkirchen",
	"Kreis Germersheim",
	"Kreis Gießen",
	"Kreis Gifhorn",
	"Kreis Goslar",
	"Kreis Gotha",
	"Kreis Grafschaft Bentheim",
	"Kreis Greiz",
	"Kreis Groß-Gerau",
	"Kreis Höxter",
	"Kreis Haßberge",
	"Kreis Hameln-Pyrmont",
	"Kreis Harburg",
	"Kreis Harz - Bergland (Oberharz)",
	"Kreis Harz - Tiefland",
	"Kreis Harz",
	"Kreis Havelland",
	"Kreis Heidenheim",
	"Kreis Heinsberg",
	"Kreis Helmstedt",
	"Kreis Herford",
	"Kreis Hersfeld-Rotenburg",
	"Kreis Herzogtum Lauenburg",
	"Kreis Hildburghausen",
	"Kreis Hildesheim",
	"Kreis Holzminden",
	"Kreis Jerichower Land",
	"Kreis Kelheim",
	"Kreis Kitzingen",
	"Kreis Kleve",
	"Kreis Konstanz",
	"Kreis Kronach",
	"Kreis Kulmbach",
	"Kreis Kusel",
	"Kreis Lörrach",
	"Kreis Lüchow-Dannenberg",
	"Kreis Lüneburg",
	"Kreis Landsberg am Lech",
	"Kreis Leer (ohne Borkum)",
	"Kreis Leer",
	"Kreis Leipzig",
	"Kreis Lichtenfels",
	"Kreis Limburg-Weilburg",
	"Kreis Lindau",
	"Kreis Lippe",
	"Kreis Ludwigsburg",
	"Kreis Ludwigslust-Parchim - Ost",
	"Kreis Ludwigslust-Parchim - West",
	"Kreis Märkisch-Oderland",
	"Kreis Mühldorf a. Inn",
	"Kreis Main-Spessart",
	"Kreis Mainz-Bingen und Stadt Mainz",
	"Kreis Mansfeld-Südharz",
	"Kreis Marburg-Biedenkopf",
	"Kreis Mayen-Koblenz",
	"Kreis Mecklenburgische Seenplatte - Nord",
	"Kreis Mecklenburgische Seenplatte - Südost",
	"Kreis Mecklenburgische Seenplatte - West",
	"Kreis Mecklenburgische Seenplatte",
	"Kreis Meißen",
	"Kreis Merzig-Wadern",
	"Kreis Mettmann",
	"Kreis Miesbach",
	"Kreis Miltenberg",
	"Kreis Minden-Lübbecke",
	"Kreis Mittelsachsen - Bergland",
	"Kreis Mittelsachsen - Tiefland",
	"Kreis Mittelsachsen",
	"Kreis Nürnberger Land",
	"Kreis Neu-Ulm",
	"Kreis Neuburg-Schrobenhausen",
	"Kreis Neumarkt i.d. OPf.",
	"Kreis Neumarkt i.d.OPf.",
	"Kreis Neunkirchen",
	"Kreis Neustadt a. d. Aisch - Bad Windsheim",
	"Kreis Neustadt a.d. Aisch - Bad Windsheim",
	"Kreis Neustadt a.d. Waldnaab",
	"Kreis Neuwied",
	"Kreis Nienburg",
	"Kreis Nordfriesland - Binnenland",
	"Kreis Nordfriesland - Küste",
	"Kreis Nordhausen",
	"Kreis Nordsachsen - Nord",
	"Kreis Nordsachsen - Süd",
	"Kreis Nordsachsen",
	"Kreis Nordwestmecklenburg - Binnenland",
	"Kreis Nordwestmecklenburg - Küste",
	"Kreis Nordwestmecklenburg",
	"Kreis Northeim",
	"Kreis Oberallgäu",
	"Kreis Oberhavel",
	"Kreis Oberspreewald-Lausitz",
	"Kreis Oder-Spree",
	"Kreis Olpe",
	"Kreis Ostallgäu",
	"Kreis Osterholz",
	"Kreis Osterode am Harz",
	"Kreis Ostholstein - Binnenland",
	"Kreis Ostholstein - Küste",
	"Kreis Ostprignitz-Ruppin",
	"Kreis Paderborn",
	"Kreis Parchim-Ludwigslust",
	"Kreis Peine",
	"Kreis Pfaffenhofen a.d. Ilm",
	"Kreis Pfaffenhofen a.d.Ilm",
	"Kreis Pinneberg (ohne Helgoland)",
	"Kreis Plön - Binnenland",
	"Kreis Plön - Küste",
	"Kreis Potsdam-Mittelmark",
	"Kreis Prignitz",
	"Kreis Rastatt",
	"Kreis Ravensburg",
	"Kreis Recklinghausen",
	"Kreis Regen",
	"Kreis Rendsburg-Eckernförde - Binnenland",
	"Kreis Rendsburg-Eckernförde - Küste",
	"Kreis Reutlingen",
	"Kreis Rhön-Grabfeld",
	"Kreis Rostock - Binnenland Nord",
	"Kreis Rostock - Binnenland Süd",
	"Kreis Rostock - Küste",
	"Kreis Rostock",
	"Kreis Rotenburg (Wümme)",
	"Kreis Roth",
	"Kreis Rottal-Inn",
	"Kreis Rottweil",
	"Kreis Sächsische Schweiz-Osterzgebirge - ostelbisches Bergland",
	"Kreis Sächsische Schweiz-Osterzgebirge - Tiefland",
	"Kreis Sächsische Schweiz-Osterzgebirge - westelbisches Bergland",
	"Kreis Sächsische Schweiz-Osterzgebirge",
	"Kreis Sömmerda",
	"Kreis Südliche Weinstraße",
	"Kreis Südwestpfalz und Stadt Pirmasens",
	"Kreis Saalfeld-Rudolstadt",
	"Kreis Saarlouis",
	"Kreis Schaumburg",
	"Kreis Schleswig-Flensburg - Binnenland",
	"Kreis Schleswig-Flensburg - Küste",
	"Kreis Schmalkalden-Meiningen",
	"Kreis Schwäbisch Hall",
	"Kreis Schwandorf",
	"Kreis Segeberg",
	"Kreis Siegen-Wittgenstein",
	"Kreis Sigmaringen",
	"Kreis Soest",
	"Kreis Sonneberg",
	"Kreis Spree-Neiße",
	"Kreis St. Wendel",
	"Kreis Stade",
	"Kreis Starnberg",
	"Kreis Steinburg",
	"Kreis Steinfurt",
	"Kreis Stendal",
	"Kreis Stormarn",
	"Kreis Straubing-Bogen und Stadt Straubing",
	"Kreis Tübingen",
	"Kreis Teltow-Fläming",
	"Kreis Tirschenreuth",
	"Kreis Traunstein",
	"Kreis Trier-Saarburg und Stadt Trier",
	"Kreis Tuttlingen",
	"Kreis Uckermark",
	"Kreis Uelzen",
	"Kreis und Stadt Ansbach",
	"Kreis und Stadt Aschaffenburg",
	"Kreis und Stadt Augsburg",
	"Kreis und Stadt Bamberg",
	"Kreis und Stadt Bayreuth",
	"Kreis und Stadt Coburg",
	"Kreis und Stadt Fürth",
	"Kreis und Stadt Göttingen",
	"Kreis und Stadt Heilbronn",
	"Kreis und Stadt Hof",
	"Kreis und Stadt Kaiserslautern",
	"Kreis und Stadt Karlsruhe",
	"Kreis und Stadt Kassel",
	"Kreis und Stadt Landshut",
	"Kreis und Stadt München",
	"Kreis und Stadt Offenbach",
	"Kreis und Stadt Oldenburg",
	"Kreis und Stadt Osnabrück",
	"Kreis und Stadt Passau",
	"Kreis und Stadt Regensburg",
	"Kreis und Stadt Rosenheim",
	"Kreis und Stadt Schweinfurt",
	"Kreis und Stadt Würzburg",
	"Kreis Unna",
	"Kreis Unterallgäu",
	"Kreis Vechta",
	"Kreis Verden",
	"Kreis Viersen",
	"Kreis Vorpommern-Greifswald - Binnenland Nord",
	"Kreis Vorpommern-Greifswald - Binnenland Süd",
	"Kreis Vorpommern-Greifswald - Küste Nord",
	"Kreis Vorpommern-Greifswald - Küste Süd",
	"Kreis Vorpommern-Greifswald",
	"Kreis Vorpommern-Rügen - Binnenland",
	"Kreis Vorpommern-Rügen - Insel Rügen",
	"Kreis Vorpommern-Rügen - Küste",
	"Kreis Vorpommern-Rügen",
	"Kreis Vulkaneifel",
	"Kreis Waldeck-Frankenberg",
	"Kreis Waldshut",
	"Kreis Warendorf",
	"Kreis Weißenburg-Gunzenhausen",
	"Kreis Weilheim-Schongau",
	"Kreis Weimarer Land",
	"Kreis Wesel",
	"Kreis Wesermarsch - Binnenland",
	"Kreis Wesermarsch - Küste",
	"Kreis Wittenberg",
	"Kreis Wittmund - Binnenland",
	"Kreis Wittmund - Küste",
	"Kreis Wolfenbüttel",
	"Kreis Wunsiedel",
	"Kreis Zwickau - Bergland",
	"Kreis Zwickau - Tiefland",
	"Kreis Zwickau",
	"Kyffhäuserkreis",
	"Lahn-Dill-Kreis",
	"Land Berlin",
	"Märkischer Kreis",
	"Müritz",
	"Main-Kinzig-Kreis und Stadt Hanau ",
	"Main-Kinzig-Kreis und Stadt Hanau",
	"Main-Tauber-Kreis",
	"Main-Taunus-Kreis",
	"Mecklenburg-Vorpommern - Mitte",
	"Mecklenburg-Vorpommern - Ost",
	"Mecklenburg-Vorpommern - West",
	"Mecklenburg-Vorpommern",
	"Mittelfranken",
	"Mittelhessen",
	"Nördliche Ostsee",
	"Nördliches Rheinland-Pfalz",
	"Nördliches Weserbergland",
	"Neckar-Odenwald-Kreis",
	"Niederbayern",
	"Niederrhein",
	"Niedersachsen - Küste",
	"Niedersachsen - Mitte",
	"Niedersachsen - nördlich der Aller",
	"Niedersachsen - Nord",
	"Niedersachsen - Süd",
	"Niedersachsen - südlich der Aller",
	"Niedersachsen - West",
	"Niedersachsen",
	"Niedersachsen/Bremen",
	"Nordbayern Zusammenfassung",
	"Norddeutschland",
	"Nordfriesische Küste",
	"Nordhessen",
	"Nordosthessen",
	"Nordrhein-Westfalen",
	"Northeimer Seenplatte",
	"Oberbayern",
	"Oberbergischer Kreis",
	"Oberfranken",
	"Oberpfalz",
	"Odenwald/Bergstraße",
	"Odenwaldkreis",
	"Ortenaukreis",
	"Osnabrücker Raum",
	"Ostalbkreis",
	"Ostfriesische Küste",
	"Ostholsteinische Seen",
	"Regierungsbezirk Arnsberg",
	"Regierungsbezirk Düsseldorf",
	"Regierungsbezirk Darmstadt",
	"Regierungsbezirk Detmold",
	"Regierungsbezirk Freiburg",
	"Regierungsbezirk Gießen",
	"Regierungsbezirk Köln",
	"Regierungsbezirk Karlsruhe",
	"Regierungsbezirk Kassel",
	"Regierungsbezirk Münster",
	"Regierungsbezirk Stuttgart",
	"Regierungsbezirk Tübingen",
	"Region Hannover",
	"Regionalverband Saarbrücken",
	"Rems-Murr-Kreis",
	"Rhön",
	"Rhein-Erft-Kreis",
	"Rhein-Hunsrück-Kreis",
	"Rhein-Kreis Neuss",
	"Rhein-Lahn-Kreis",
	"Rhein-Main-Gebiet",
	"Rhein-Neckar-Kreis und Stadt Heidelberg",
	"Rhein-Pfalz-Kreis und Stadt Ludwigshafen ",
	"Rhein-Pfalz-Kreis und Stadt Ludwigshafen",
	"Rhein-Sieg Kreis",
	"Rhein-Sieg-Kreis",
	"Rheingau-Taunus-Kreis",
	"Rheinhessen",
	"Rheinisch-Bergischer Kreis",
	"Rheinland-Pfalz - Nord",
	"Rheinland-Pfalz - Süd",
	"Rheinland-Pfalz",
	"Rheinland-Pfalz/Saarland",
	"Rigaischer Meerbusen",
	"Rothsee",
	"Südöstliche Ostsee",
	"Südbayern Zusammenfassung",
	"Südliche Ostsee",
	"Südliches Rheinland-Pfalz",
	"Südliches Weserbergland",
	"Südwestliche Nordsee",
	"Saale-Holzland-Kreis",
	"Saale-Orla-Kreis",
	"Saalekreis",
	"Saar-Region",
	"Saarland - Ost",
	"Saarland - West",
	"Saarland",
	"Saarpfalz-Kreis",
	"Sachsen - Nord",
	"Sachsen - Ost",
	"Sachsen - West",
	"Sachsen",
	"Sachsen-Anhalt - Mitte",
	"Sachsen-Anhalt - Nord",
	"Sachsen-Anhalt - Ost",
	"Sachsen-Anhalt - Süd",
	"Sachsen-Anhalt",
	"Salzlandkreis",
	"Sauerland",
	"Schleswig-Holstein - Binnenland",
	"Schleswig-Holstein - Küste (Nordsee)",
	"Schleswig-Holstein - Küste (Ostsee)",
	"Schleswig-Holstein - Mitte",
	"Schleswig-Holstein - Nordsee",
	"Schleswig-Holstein - Ostsee",
	"Schleswig-Holstein",
	"Schleswig-Holstein/Hamburg",
	"Schliersee",
	"Schwaben",
	"Schwalm-Eder-Kreis",
	"Schwarzwald-Baar-Kreis",
	"Seegebiet Helgoland",
	"Simssee",
	"Skagerrak",
	"StädteRegion Aachen",
	"Stadt Amberg",
	"Stadt Baden-Baden",
	"Stadt Bielefeld",
	"Stadt Bochum",
	"Stadt Bottrop",
	"Stadt Brandenburg",
	"Stadt Braunschweig",
	"Stadt Bremerhaven",
	"Stadt Chemnitz",
	"Stadt Cottbus",
	"Stadt Düsseldorf",
	"Stadt Delmenhorst",
	"Stadt Dessau-Roßlau",
	"Stadt Dortmund",
	"Stadt Dresden",
	"Stadt Duisburg",
	"Stadt Eisenach",
	"Stadt Emden",
	"Stadt Erfurt",
	"Stadt Erlangen",
	"Stadt Essen",
	"Stadt Flensburg",
	"Stadt Frankenthal",
	"Stadt Frankfurt (Oder)",
	"Stadt Frankfurt am Main",
	"Stadt Gelsenkirchen",
	"Stadt Gera",
	"Stadt Hagen",
	"Stadt Halle (Saale)",
	"Stadt Hamm",
	"Stadt Herne",
	"Stadt Ingolstadt",
	"Stadt Jena",
	"Stadt Köln",
	"Stadt Kaufbeuren",
	"Stadt Kempten (Allgäu)",
	"Stadt Kiel",
	"Stadt Koblenz",
	"Stadt Krefeld",
	"Stadt Landau in der Pfalz",
	"Stadt Leipzig",
	"Stadt Leverkusen",
	"Stadt Mönchengladbach",
	"Stadt Mülheim an der Ruhr",
	"Stadt Münster",
	"Stadt Magdeburg",
	"Stadt Mannheim",
	"Stadt Memmingen",
	"Stadt Nürnberg",
	"Stadt Neumünster",
	"Stadt Neustadt an der Weinstraße",
	"Stadt Oberhausen",
	"Stadt Potsdam",
	"Stadt Remscheid",
	"Stadt Salzgitter",
	"Stadt Schwabach",
	"Stadt Schwerin",
	"Stadt Solingen",
	"Stadt Speyer",
	"Stadt Stuttgart",
	"Stadt Suhl",
	"Stadt Weiden in der Oberpfalz",
	"Stadt Weimar",
	"Stadt Wiesbaden",
	"Stadt Wilhelmshaven",
	"Stadt Wolfsburg",
	"Stadt Worms",
	"Stadt Wuppertal",
	"Stadt Zweibrücken",
	"Staffel-/Riegsee",
	"Starnberger See",
	"Steinhuder Meer",
	"Taunus",
	"Tegernsee",
	"Thüringen - Mitte-Nord",
	"Thüringen - Ost",
	"Thüringen - Süd",
	"Thüringen",
	"Unstrut-Hainich-Kreis",
	"Unterfranken",
	"Utsira",
	"Viking",
	"Vogelsbergkreis",
	"Vogtlandkreis - Bergland",
	"Vogtlandkreis - Tiefland",
	"Vogtlandkreis",
	"Wörthsee",
	"Waginger/Tachinger See",
	"Walchensee",
	"Warngebiet im DWD *",
	"Wartburgkreis",
	"Werra-Meissner-Kreis",
	"Weser-Ems-Gebiet",
	"Weser-Leine-Bergland",
	"Westerwald/Biedenkopf",
	"Westerwaldkreis",
	"Westliche Ostsee",
	"Westliches Münsterland",
	"Westliches Ruhrgebiet",
	"Wetteraukreis",
	"Zentrale Ostsee",
	"Zollernalbkreis",
	"Zwischenahner Meer"
];
