/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "Create states for rainradar": {                 "en": "Create objects to include rain radar into your visualization.", "de": "Objekte erstellen um Regenradar in die Visualisierung einzubinden", "ru": "Создавайте объекты, чтобы включить дождевой радар в вашу визуализацию.", "pt": "Criar objetos para incluir radar de chuva em sua visualização.", "nl": "Maak objecten om regenradar in uw visualisatie op te nemen.", "fr": "Créez des objets pour inclure un radar de pluie dans votre visualisation.", "it": "Crea oggetti per includere il radar della pioggia nella tua visualizzazione.", "es": "Cree objetos para incluir un radar de lluvia en su visualización.", "pl": "Twórz obiekty, aby uwzględnić w wizualizacji radar deszczu.", "zh-cn": "创建对象以将气象雷达添加到您的可视化中。"},
    "Get map for warning": {                         "en": "Get map for warning",                             "de": "Gewünschte Karte für die Wetterwarnung auswählen", "ru": "Получить карту для предупреждения",               "pt": "Obter mapa para aviso",                           "nl": "Krijg kaart voor waarschuwing",                   "fr": "Obtenir la carte pour l'avertissement",           "it": "Ottieni la mappa per avvertire",                  "es": "Obtener mapa para advertencia",                   "pl": "Pobierz mapę z ostrzeżeniem",                     "zh-cn": "获取地图警告"},
    "Number of warnings": {                          "en": "Number of warnings",                              "de": "Anzahl der Warnmeldungen",                        "ru": "Количество предупреждений",                       "pt": "Número de avisos",                                "nl": "Aantal waarschuwingen",                           "fr": "Nombre d'avertissements",                         "it": "Numero di avvertimenti",                          "es": "Número de advertencias",                          "pl": "Liczba ostrzeżeń",                                "zh-cn": "警告次数"},
    "Region": {                                      "en": "Region",                                          "de": "Region",                                          "ru": "Область",                                         "pt": "Região",                                          "nl": "Regio",                                           "fr": "Région",                                          "it": "Regione",                                         "es": "Región",                                          "pl": "Region",                                          "zh-cn": "地区"},
    "no map": {                                      "en": "no map",                                          "de": "keine Karte",                                     "ru": "без карты",                                       "pt": "sem mapa",                                        "nl": "geen kaart",                                      "fr": "pas de carte",                                    "it": "nessuna mappa",                                   "es": "sin mapa",                                        "pl": "bez mapy",                                        "zh-cn": "没有地图"},
};